import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// Run explicitly when a reviewed research snapshot is ready. App builds use the
// pinned generated file, so another agent's ongoing research cannot change a build.
const here = dirname(fileURLToPath(import.meta.url));
const [ledgerArg, scanArg, ...extraArgs] = process.argv.slice(2);
if (!ledgerArg || !scanArg || extraArgs.length) {
  console.error('Usage: node scripts/prepare-data.mjs <reviewed-ledger.json> <reviewed-barcode-lookup.json>');
  process.exit(2);
}
const ledgerPath = resolve(process.cwd(), ledgerArg);
const scanPath = resolve(process.cwd(), scanArg);
const [ledgerBytes, scanBytes] = await Promise.all([readFile(ledgerPath), readFile(scanPath)]);
const ledger = JSON.parse(ledgerBytes);
const scan = JSON.parse(scanBytes);

const sha256 = (bytes) => createHash('sha256').update(bytes).digest('hex');
const assert = (condition, message) => { if (!condition) throw new Error(message); };
const checksumValid = (digits) => {
  if (!/^\d{12,14}$/.test(digits)) return false;
  let sum = 0;
  for (let i = digits.length - 1, position = 0; i >= 0; i--, position++) {
    sum += Number(digits[i]) * (position % 2 ? 3 : 1);
  }
  return sum % 10 === 0;
};

const catalog = {};
for (const row of ledger.catalog) {
  const id = row.din_npn;
  assert(typeof id === 'string' && /^\d{8}$/.test(id), `Invalid DIN/NPN: ${id}`);
  assert(!catalog[id], `Duplicate DIN/NPN: ${id}`);
  catalog[id] = {
    brandName: row.brand_name,
    chemicalName: row.chemical_name,
    strength: row.strength,
    dosageForm: row.dosage_form,
    manufacturer: row.manufacturer,
    pdfPage: row.pdf_page,
  };
}

const barcodes = {};
for (const [gtin14, row] of Object.entries(scan.lookup_by_gtin14)) {
  assert(/^\d{14}$/.test(gtin14) && checksumValid(gtin14), `Invalid GTIN: ${gtin14}`);
  assert(catalog[row.din_npn], `Barcode ${gtin14} points outside catalog`);
  assert(!barcodes[gtin14], `Duplicate GTIN: ${gtin14}`);
  barcodes[gtin14] = {
    identifier: row.din_npn,
    hasLiveSource: row.has_live_source,
    publishedBarcodes: row.published_barcodes,
    sources: row.sources.map(({ title, url, type, source_date }) => ({ title, url, type, sourceDate: source_date })),
  };
}

assert(Object.keys(catalog).length === 507, 'Unexpected catalog count');
assert(Object.keys(barcodes).length === 289, 'Unexpected barcode count');
assert(scan.metadata.official_list_url === ledger.metadata.official_list_url, 'Source URL mismatch');
const snapshot = {
  listLabel: `${ledger.metadata.official_list_last_update} research snapshot`,
  listUpdateLabel: ledger.metadata.official_list_last_update,
  researchDate: ledger.metadata.research_date,
  catalogCount: Object.keys(catalog).length,
  barcodeCount: Object.keys(barcodes).length,
  officialListUrl: ledger.metadata.official_list_url,
  sourcePdfSha256: ledger.metadata.official_pdf_sha256,
  ledgerSha256: sha256(ledgerBytes),
  barcodeLookupSha256: sha256(scanBytes),
};

const code = `// Generated by scripts/prepare-data.mjs from the pinned September 2026 research files.\n` +
  `// This intentionally omits unverified leads and unresolved products.\n` +
  `export const SNAPSHOT = Object.freeze(${JSON.stringify(snapshot, null, 2)});\n` +
  `export const CATALOG = Object.freeze(${JSON.stringify(catalog)});\n` +
  `export const BARCODE_LOOKUP = Object.freeze(${JSON.stringify(barcodes)});\n`;
await writeFile(resolve(here, '../src/catalog.mjs'), code);
await writeFile(resolve(here, '../data-manifest.json'), JSON.stringify(snapshot, null, 2) + '\n');
console.log(`Pinned ${snapshot.catalogCount} identifiers and ${snapshot.barcodeCount} barcodes`);
